#!/usr/bin/env python3

import subprocess

def list_installed_pkg_manully():
    installed_pkgs = subprocess.check_output(['pacman', '-Qeq'], text=True).splitlines()
    paclog_output = subprocess.check_output(['paclog', '--action=install'], text=True).splitlines()

    installed_pkgs_set = set(installed_pkgs)
    seen_pkgs = set()

    filtered_paclog_output = []
    for line in reversed(paclog_output):
        parts = line.split()
        if len(parts) < 5:
            continue

        date_time = parts[0]
        pkg = parts[3]
        version = parts[4]
        if pkg in installed_pkgs_set and pkg not in seen_pkgs:
            filtered_paclog_output.append(f"{date_time}  {pkg:<30} {version}")

            seen_pkgs.add(pkg)

    for line in filtered_paclog_output:
        print(line)

if __name__ == "__main__":
    list_installed_pkg_manully()
